[[language]]
name="javascript"
indent={tab-width=2,unit="\t"}
[[language]]
name="c"
indent={tab-width=2,unit="\t"}
[[language]]
name="cpp"
indent={tab-width=2,unit="\t"}
[[language]]
name="html"
indent={tab-width=2,unit="\t"}
[[language]]
name="xml"
indent={tab-width=2,unit="\t"}
[[language]]
name="markdown"
indent={tab-width=2,unit="\t"}
[[language]]
name="qml"
indent={tab-width=2,unit="\t"}
[[language]]
name="css"
indent={tab-width=2,unit="\t"}
[[language]]
name="toml"
indent={tab-width=2,unit="\t"}
[[language]]
name="json"
indent={tab-width=2,unit="\t"}
