[audio]
enable_overdrive = true

[bar]
order = [ "main" ]

    [bar.main]
    background_opacity = 0.79999998211860657
    capsule = true
    capsule_thickness = 0.79999998584389687
    end = [ "media", "tray", "bluetooth", "network", "volume", "brightness", "battery" ]
    layer = "top"
    margin_edge = 4
    margin_ends = 4
    padding = 8
    reserve_space = true
    shadow = false
    smart_auto_hide = false
    start = [ "launcher", "workspaces" ]
    thickness = 32

[battery]
warning_threshold = 20

[brightness]
enable_ddcutil = true

[calendar]
enabled = true
event_date_format = "%F"
event_time_format = "%R"

[control_center]
width = 960

    [control_center.calendar]
    show_week_numbers = true

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 120.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 300.0

[location]
latitude = 35.700000000000003
longitude = 139.80000000000001

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1920.0
    cy = 1978.0
    output = "DP-2"
    placement_height = 2160.0
    placement_width = 3840.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1920.0
    cy = 1978.0
    output = "HDMI-A-1"
    placement_height = 2160.0
    placement_width = 3840.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 256.0
    cx = 960.0
    cy = 824.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 256.0
    box_width = 256.0
    cx = 960.0
    cy = 536.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        center_text = true
        circle = false
        clock_style = "analog"
        color = "on_surface"
        font_family = ""
        format = "{:%H:%M}"
        shadow = true
        timezone = ""

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 192.0
    box_width = 384.0
    cx = 960.0
    cy = 1016.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = -0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        hide_when_no_media = true
        layout = "horizontal"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 128.0
    box_width = 256.0
    cx = 960.0
    cy = 248.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background = false
        format = "%R"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 32.0
    box_width = 256.0
    cx = 960.0
    cy = 168.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background = false
        color = "on_surface_variant"
        format = "%F"

[nightlight]
enabled = true

[osd.kinds]
keyboard_layout = false

[shell]
avatar_path = "/home/mcbeeringi/.face"
date_format = "%F"
font_family = "monospace"
polkit_agent = true
settings_window_translucent = true
time_format = "%R"

    [shell.launcher]
    app_grid = true
    categories = false
    compact = true
    show_app_actions = true

    [shell.panel]
    shadow = false
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.session]
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        label = "lock"
        shortcut = "l"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = true
        label = "suspend"
        shortcut = "s"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        label = "exit"
        shortcut = "e"
        variant = "default"

        [[shell.session.actions]]
        action = "command"
        command = "systemctl kexec"
        countdown_seconds = 0.0
        enabled = true
        glyph = "reboot"
        label = "kexec"
        shortcut = "k"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        label = "reboot"
        shortcut = "r"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        label = "poweroff"
        shortcut = "p"
        variant = "destructive"

[theme]
community_palette = "One"
custom_palette = "6ca"
source = "custom"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/mcbeeringi/Pictures/wp"
transition = [ "fade" ]

    [wallpaper.default]
    path = "/home/mcbeeringi/Pictures/wp/hanabi.jpg"

    [wallpaper.last]
    path = "/home/mcbeeringi/Pictures/wp/hanabi.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/mcbeeringi/Pictures/wp/hanabi.jpg"

[weather]
enabled = false

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.brightness]
show_label = false

[widget.clock]
format = "%F %R"

[widget.media]
album_art_only = true
hide_when_no_media = true

[widget.network]
show_label = false

[widget.volume]
show_label = false
