[audio]
enable_overdrive = true

[bar]
order = [ "main" ]

    [bar.main]
    background_opacity = 0.8
    capsule = true
    capsule_thickness = 0.8
    end = [ "media", "tray", "bluetooth", "network", "volume", "brightness", "battery" ]
    layer = "top"
    margin_edge = 0
    margin_ends = 0
    shadow = false
    start = [ "launcher", "workspaces" ]
    thickness = 32

[battery]
warning_threshold = 20

[brightness]
enable_ddcutil = true

[calendar]
enabled = true
event_date_format = "%F"
event_time_format = "%R"

[control_center]
width = 960

    [control_center.calendar]
    show_week_numbers = true

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "mic_mute"

    [[control_center.shortcuts]]
    type = "dark_mode"


[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 120.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 300.0

[location]
latitude = 35.7
longitude = 139.8

[lockscreen_widgets]
enabled = true

[nightlight]
enabled = true

[osd.kinds]
keyboard_layout = false

[shell]
avatar_path = "~/.face"
date_format = "%F"
font_family = "monospace"
polkit_agent = true
settings_window_translucent = true
time_format = "%R"

    [shell.launcher]
    app_grid = true
    categories = false
    compact = true
    show_app_actions = true

    [shell.panel]
    shadow = false
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.session]
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        label = "lock"
        shortcut = "l"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = true
        label = "suspend"
        shortcut = "s"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        label = "exit"
        shortcut = "e"
        variant = "default"

        [[shell.session.actions]]
        action = "command"
        command = "systemctl kexec"
        countdown_seconds = 0.0
        enabled = true
        glyph = "reboot"
        label = "kexec"
        shortcut = "k"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        label = "reboot"
        shortcut = "r"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        label = "poweroff"
        shortcut = "p"
        variant = "destructive"

[theme]
community_palette = "One"
custom_palette = "6ca"
source = "custom"
wallpaper_scheme = "m3-content"

[wallpaper]
transition = [ "fade" ]

[weather]
enabled = false

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.brightness]
show_label = false

[widget.clock]
format = "%F %R"

[widget.media]
album_art_only = true
hide_when_no_media = true

[widget.network]
show_label = false

[widget.volume]
show_label = false
